name: Actionlint

on:
  push:
    paths:
      - '.github/workflows/**'
      - '.github/actions/**'
  pull_request:
    paths:
      - '.github/workflows/**'
      - '.github/actions/**'

permissions:
  contents: read

jobs:
  actionlint:
    name: Actionlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run actionlint
        uses: rhysd/actionlint@v1.7.7
